rules.lowercamelcase_package = true
rules.uppercamelcase_module = true
option.prefix_interface = "ifc_"
rules.prefix_interface = true
option.prefix_instance = "u_"
rules.prefix_instance = true
option.prefix_label = "l_"
rules.generate_case_with_label = true
rules.generate_for_with_label = true
rules.generate_if_with_label = true
option.prefix_inout = "b_"
rules.prefix_inout = true
option.prefix_input = "i_"
rules.prefix_input = true
option.prefix_output = "o_"
rules.prefix_output = true
option.re_required_port_interface = "^[a-z]+[a-zA-Z0-9_]*$"
rules.re_required_port_interface = true
option.re_required_function = "^([a-z]{1,1}[a-z0-9]{0,9}|f_[a-zA-Z0-9_]+)$"
rules.re_required_function = true
option.re_required_localparam = "^[A-Z]+[A-Z0-9_]*)$"
rules.re_required_localparam = true
option.re_required_parameter = "^[A-Z]+[A-Z0-9_]*)$"
rules.re_required_parameter = true
option.re_required_genvar = "^[a-z]{1,3}$"
rules.re_required_genvar = true
