rules.blocking_assignment_in_always_ff = true
rules.non_blocking_assignment_in_always_comb = true
rules.enum_with_type = true
rules.keyword_forbidden_priority = true
rules.keyword_forbidden_unique = true
rules.keyword_forbidden_unique0 = true
rules.action_block_with_side_effects = true
rules.default_nettype_none = true
rules.function_same_as_system_function = true
rules.keyword_forbidden_wire_reg = true
rules.non_ansi_module = true
rules.localparam_type_twostate = true
rules.parameter_type_twostate = true
rules.localparam_explicit_type = true
rules.parameter_explicit_type = true
rules.parameter_default_value = true
rules.parameter_in_generate = true
rules.parameter_in_package = true
rules.genvar_declaration_in_loop = true
rules.genvar_declaration_out_loop = false
rules.keyword_forbidden_generate = true
rules.keyword_required_generate = false
rules.multiline_for_begin = true
rules.multiline_if = true
rules.inout_with_tri = true
rules.input_with_var = true
rules.output_with_var = true
rules.interface_port_with_modport = true
