[package]
name = "svlint"
version = "0.1.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/svlint"
keywords = ["lint", "verilog", "systemverilog"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
description = "SystemVerilog linter"
edition = "2018"

[dependencies]
colored      = "1.6"
failure      = "0.1"
regex        = "1.0"
serde        = "1.0"
serde_derive = "1.0"
serde_regex  = "0.4"
structopt    = "0.3"
sv-parser    = {version = "0.2", path = "../sv-parser/sv-parser"}
term         = "0.5"
toml         = "0.4"
