name: Run mdgen

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - name: BUILDENV
        id: BUILDENV
        shell: bash
        run: |
          rm -f BUILDENV
          rustup --version >> BUILDENV
          cargo --version >> BUILDENV
          rustc --version >> BUILDENV
          cat BUILDENV
          echo "REPOSITORY=$(grep repository Cargo.toml | sed 's/[^\"]*\"\([^\"]*\).*/\1/')" >> $GITHUB_OUTPUT
          echo "GIT_REVISION=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "DATETIME_ISO8601=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('BUILDENV', '**/Cargo.lock') }}
      - id: mdgen
        run: |
          cargo run --bin=mdgen
          (git diff --quiet MANUAL.md && \
            echo "manual_md=not_changed" >> $GITHUB_OUTPUT) || \
            echo "manual_md=is_changed" >> $GITHUB_OUTPUT
          sed \
            -e 's/^## Rule: /\\clearpage\n## Rule: /' \
            -e 's/^## Ruleset: /\\clearpage\n## Ruleset: /' \
            MANUAL.md > MANUAL.intermediateTex.md
          rm -f BUILDENV
      - if: ${{ steps.mdgen.outputs.manual_md == 'is_changed' }}
        uses: docker://pandoc/latex:2.18
        with:
          args: >-
            -i MANUAL.intermediateTex.md
            --template=md/MANUAL_template.tex
            --metadata "title=Svlint Manual"
            --metadata "subtitle=DEVELOPMENT ${{steps.BUILDENV.outputs.GIT_REVISION}}"
            --metadata "author=${{steps.BUILDENV.outputs.REPOSITORY}}"
            --metadata "date=${{steps.BUILDENV.outputs.DATETIME_ISO8601}}"
            --metadata "keywords=SystemVerilog"
            --metadata "keywords=Verilog"
            --metadata "keywords=IEEE1800-2017"
            --metadata "keywords=lint"
            --metadata "keywords=svlint"
            --metadata "keywords=sv-parser"
            --metadata "keywords=svls"
            --toc
            --toc-depth=2
            --variable=colorlinks
            --variable=papersize:a4
            -o MANUAL.pdf
      - run: rm -f *.intermediate*.*
      - uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
