name: Run mdgen

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - name: BUILDENV
        shell: bash
        run: |
          rm -f BUILDENV
          rustup --version >> BUILDENV
          cargo --version >> BUILDENV
          rustc --version >> BUILDENV
          cat BUILDENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('BUILDENV', '**/Cargo.lock') }}
      - id: mdgen
        run: |
          cargo run --bin=mdgen
          (git diff --quiet MANUAL.md && \
            echo "manual_md=not_changed" >> $GITHUB_OUTPUT) || \
            echo "manual_md=is_changed" >> $GITHUB_OUTPUT
          rm -f BUILDENV
      - if: ${{ steps.mdgen.outputs.manual_md == 'is_changed' }}
        uses: docker://pandoc/latex:2.18
        with:
          args: >-
            -i MANUAL.md
            -o MANUAL.pdf
      - uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
