name: Run mdgen

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - name: BUILDENV
        shell: bash
        run: |
          rm -f BUILDENV
          rustup --version >> BUILDENV
          cargo --version >> BUILDENV
          rustc --version >> BUILDENV
          cat BUILDENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('BUILDENV', '**/Cargo.lock') }}
      - run: |
          cargo run --bin=mdgen
          rm -f BUILDENV
      - id: is_changed_md
        uses: EndBug/add-and-commit@v9
        with:
          commit: --dry-run
      - if: steps.is_changed_md.outputs.committed == true
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -i MANUAL.md
            -o MANUAL.pdf
      - uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
