name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate Variables
        id: CALCVARS
        shell: bash
        run: |
          echo "REPOSITORY=$(grep repository Cargo.toml | sed 's/[^\"]*\"\([^\"]*\).*/\1/')" >> $GITHUB_OUTPUT
          echo "DATE_ISO8601=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Modify Markdown
        run: |
          make MANUAL.intermediateTex.md
      - uses: docker://pandoc/extra:3.1
        with:
          args: >-
            -i MANUAL.intermediateTex.md
            -f markdown+lists_without_preceding_blankline
            --template=md/MANUAL_template.tex
            --metadata "title=Svlint Manual"
            --metadata "subtitle=${{github.ref_name}}"
            --metadata "author=${{steps.CALCVARS.outputs.REPOSITORY}}"
            --metadata "date=${{steps.CALCVARS.outputs.DATE_ISO8601}}"
            --metadata "keywords=SystemVerilog"
            --metadata "keywords=Verilog"
            --metadata "keywords=IEEE1800-2017"
            --metadata "keywords=lint"
            --metadata "keywords=svlint"
            --metadata "keywords=sv-parser"
            --metadata "keywords=svls"
            --toc
            --toc-depth=2
            --variable=colorlinks
            --variable=papersize:a4
            -o svlint_MANUAL_${{github.ref_name}}.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: svlint_MANUAL_${{github.ref_name}}.pdf

  build_exe:
    needs: build_pdf

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/download-artifact@v3

      - if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - if: matrix.os == 'ubuntu-latest'
        run: make release_lnx VERSION=${{github.ref_name}}
        shell: sh

      - if: matrix.os == 'macOS-latest'
        run: |
          rustup target add x86_64-apple-darwin
          make release_mac_x86_64  VERSION=${{github.ref_name}}
          make release_mac_aarch64 VERSION=${{github.ref_name}}
        shell: sh

      - if: matrix.os == 'windows-latest'
        run: make release_win VERSION=${{github.ref_name}}
        shell: bash

      - uses: softprops/action-gh-release@v1
        with:
          body: '[Changelog](https://github.com/dalance/svlint/blob/master/CHANGELOG.md)'
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
